Role.create!([
  {name: "Admin"},
  {name: "Member"},
  {name: "Alumni"},
  {name: "Event Planner"}
])

# Scrapped TAMU's catalog for every bachelor degree
Major.create!([
  {name: "International Studies"},
  {name: "Kinesiology"},
  {name: "Agribusiness"},
  {name: "Agricultural Economics"},
  {name: "Agricultural Communications and Journalism"},
  {name: "Agricultural Leadership and Development"},
  {name: "Agricultural Science"},
  {name: "Animal Science"},
  {name: "Biochemistry"},
  {name: "Genetics"},
  {name: "Agricultural Systems Management"},
  {name: "Biological and Agricultural Engineering"},
  {name: "Ecology and Conservation Biology"},
  {name: "Entomology"},
  {name: "Forensic and Investigative Sciences"},
  {name: "Food Science and Technology"},
  {name: "Food Systems Industry Management"},
  {name: "Horticulture"},
  {name: "Nutrition"},
  {name: "Bioenvironmental Sciences"},
  {name: "Poultry Science"},
  {name: "Rangeland Ecology and Management"},
  {name: "Rangeland, Wildlife and Fisheries Management"},
  {name: "Recreation, Park and Tourism Sciences"},
  {name: "Plant and Environmental Soil Science"},
  {name: "Turfgrass Science"},
  {name: "Environmental Design Architectural Studies"},
  {name: "Construction Science"},
  {name: "Landscape Architecture"},
  {name: "Urban and Regional Planning"},
  {name: "Biomedical Sciences"},
  {name: "Environmental Studies"},
  {name: "Neuroscience"},
  {name: "University Studies"},
  {name: "Anthropology"},
  {name: "Meteorology"},
  {name: "Biology"},
  {name: "Microbiology"},
  {name: "Molecular and Cell Biology"},
  {name: "Zoology"},
  {name: "Chemistry"},
  {name: "Communication"},
  {name: "Telecommunication Media Studies"},
  {name: "Economics"},
  {name: "English"},
  {name: "Environmental Geosciences"},
  {name: "Geographic Information Science and Technology"},
  {name: "Geography"},
  {name: "Geology"},
  {name: "Geophysics"},
  {name: "Classics"},
  {name: "Modern Languages"},
  {name: "Spanish"},
  {name: "History"},
  {name: "Applied Mathematical Sciences"},
  {name: "Mathematics"},
  {name: "Oceanography"},
  {name: "Philosophy"},
  {name: "Physics"},
  {name: "Psychology"},
  {name: "Sociology"},
  {name: "Women's and Gender Studies"},
  {name: "Statistics"},
  {name: "Business Administration"},
  {name: "Accounting"},
  {name: "Finance"},
  {name: "Management Information Systems"},
  {name: "Supply Chain Management"},
  {name: "Management"},
  {name: "Marketing"},
  {name: "Dental Hygiene"},
  {name: "Human Resource Development"},
  {name: "Sport Management"},
  {name: "Education"},
  {name: "Aerospace Engineering"},
  {name: "Biomedical Engineering"},
  {name: "Chemical Engineering"},
  {name: "Civil Engineering"},
  {name: "Environmental Engineering"},
  {name: "Computer Engineering"},
  {name: "Computer Science"},
  {name: "Computing"},
  {name: "Electrical Engineering"},
  {name: "Electronic Systems Engineering Technology"},
  {name: "Industrial Distribution"},
  {name: "Manufacturing and Mechanical Engineering Technology"},
  {name: "Multidisciplinary Engineering Technology"},
  {name: "Technology Management"},
  {name: "Industrial Engineering"},
  {name: "Materials Science and Engineering"},
  {name: "Mechanical Engineering"},
  {name: "Architectural Engineering"},
  {name: "Interdisciplinary Engineering"},
  {name: "Nuclear Engineering"},
  {name: "Ocean Engineering"},
  {name: "Petroleum Engineering"},
  {name: "Political Science"},
  {name: "Nursing"},
  {name: "Performance Studies"},
  {name: "Visualization"},
  {name: "Public Health"},
  {name: "Community Health*"},
  {name: "Health*"},
  {name: "Maritime Studies"},
  {name: "Marine Biology"},
  {name: "Marine Fisheries"},
  {name: "Marine Engineering Technology"},
  {name: "Coastal Environmental Science and Society"},
  {name: "Marine Sciences"},
  {name: "Maritime Business Administration"},
  {name: "Marine Transportation"}
])